### ISSUE TITLE
Generate Mask for custom video

### ISSUE THREAD

**Issue by italosalgado14** [ruiliu-ai/DSTT#14]
Hi, thanks for the code!

Any code, technique or framework recommendation to perform the necessary segmentation/mask (like --mask examples/schoolgirls) as input for your algorithm? Thanks in advance!

**Comment by ruiliu-ai** [comment]
You can refer to segmentation algorithms such as maskrcnn (https://github.com/matterport/Mask_RCNN).

**Comment by italosalgado14** [comment]
I use them and its works!. To persons, y recommend MODNet + Filters Preprocesing for generate faster masks.
