### ISSUE TITLE
Some question about the paper!

### ISSUE THREAD

**Issue by jiaaihhy** [ruiliu-ai/DSTT#3]
In your paper Section 3.2, split the F in the s^2 zones, Then total number is t * s^2 * n, why this number need to * n , should the number is t * s^2? 
Looking forward your reply

**Comment by ruiliu-ai** [comment]
here n = h / (12 s) * w / (12 s), so we have s^2 * n = h / 12 * w / 12, which is the total number of tokens for each frame.

**Comment by ruiliu-ai** [comment]
here n = h / (12 s) * w / (12 s), so we have s^2 * n = h / 12 * w / 12, which is the total number of tokens for each frame.

**Comment by jiaaihhy** [comment]
for example, like an image is 144 * 144,  such as s = 4, then n = h / (12 s) * w / (12 s) =  3 * 3 = 9 , then s ** 2 = 16,  then n * s^2 = 144, you means the total number of tokens is 144? not s ^2 = 16?    this mean one pixel is a token, not one patch is a token? any problems?   
Thank you!

**Comment by ruiliu-ai** [comment]
Yes, one pixel is a token for the down-sampled feature map
