### ISSUE TITLE
How to align the consecutive frames or patches?

### ISSUE THREAD

**Issue by junpan19** [ruiliu-ai/DSTT#6]

**Comment by junpan19** [comment]
Nice work! I hope to know whether use alignment, such as optical flow or affine transformation, to these image patches?

**Comment by ruiliu-ai** [comment]
No explicit alignment adopted in this work, but I think the network implicitly learns to align these patches.

**Comment by sangruolin** [comment]
Nice work!, I want to test the effect of the code in the Davis and YouTube-VOS test set, but each video in the test set only corresponds to a mask of the initial frame, how should I process the test set
